[build]
  builder = "nixpacks"
  buildCommand = "npm run build:all"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/ping"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10

[phases.setup]
  nixPkgs = ["nodejs", "npm"]

[phases.build]
  cmds = ["npm run build:all"]

[phases.deploy]
  cmd = "npm start"